---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: k8tz
    namespace: flux-system
  values:
    namespace: null
    createNamespace: false
    timezone: Europe/Zurich
    cronJobTimeZone: true
    webhook:
      certManager:
        enabled: true
        issuerRef:
          kind: Issuer
          name: k8tz-webhook-issuer
