---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: renovate-operator
  labels:
    internal-gateway-access: 'true'