---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app renovate-operator
  namespace: flux-system
spec:
  targetNamespace: &namespace renovate
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: renovate-operator
      namespace: *namespace
  path: ./cluster/kubernetes/apps/renovate-operator/renovate-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app renovate-operator-jobs
  namespace: flux-system
spec:
  targetNamespace: renovate
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: renovate-operator
  path: ./cluster/kubernetes/apps/renovate-operator/renovate-operator/jobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app renovate-operator-ingress
  namespace: flux-system
spec:
  targetNamespace: renovate
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      failed: status.parents[0].conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'False')
      current: status.parents[0].conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'True')
  dependsOn:
    - name: envoy-gateway-resources
  path: ./cluster/kubernetes/apps/renovate-operator/renovate-operator/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m