---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: renovate-dashboard
  namespace: renovate
  labels:
    route-label: external-dns-internal
  annotations:
    gatus.home-operations.com/enabled: 'true'
spec:
  hostnames:
    - renovate.local.cjsolsen.com
  parentRefs:
    - name: internal-gateway
      namespace: network
      sectionName: renovate-dashboard
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: renovate-operator
          port: 8081
